### ISSUE TITLE
Create a plugin system

### ISSUE THREAD

**Issue by fnando** [stellar/stellar-cli#1776]
- [x] `stellar plugin --list [--installed]` also called `stellar plugin ls`: list plugins by using Github search
      (`--installed` will show installed plugins only)
- [ ] `stellar plugin add [SOURCE]`: install a plugin. `SOURCE` can be a local
      directory, a git url (e.g. `https://github.com/user/repo.git#ref`), or a
      Github `user/repo#ref`.
- [ ] `stellar plugin remove PLUGIN`: remove a plugin.
- [ ] `stellar plugin update`: update all plugins; must respect git refs.

## Plugin structure

A plugin is a directory that has a `bin/` directory and `manifest.toml` file.
For now, only `stellar contract bindings [TYPE]` plugins will be supported. For
instance, if you want to generate bindings for Ruby, you could have an
executable binary as `bin/stellar-contract-bindings-ruby` in your repository.

The manifest:

```toml
# define the manifest version.
manifest = "1.0"

# All fields are required.
description = "generate Python language bindings for Stellar Soroban smart contracts."
url = "https://github.com/lightsail-network/stellar-contract-bindings"
version = "0.1.0"
```

## Reference output

```console
$ stellar plugin list
name: lightsail-network/stellar-contract-bindings
description: generate language bindings for Stellar Soroban smart contracts.
url: https://github.com/lightsail-network/stellar-contract-bindings
installed: no

name: fnando/stellar-contract-bindings-ruby
description: generate Ruby bindings for Stellar Soroban smart contracts.
url: https://github.com/fnando/stellar-contract-bindings-ruby
installed: no

$ stellar plugin add lightsail-network/stellar-contract-bindings
❓ Are you sure you want to continue (y/n)? y
ℹ️ Installing plugin "lightsail-network/stellar-contract-bindings"
✅ Plugin was installed!
📄 For instructions, visit https://github.com/lightsail-network/stellar-contract-bindings

$ stellar plugin list --installed
name: lightsail-network/stellar-contract-bindings
description: generate language bindings for Stellar Soroban smart contracts.
url: https://github.com/lightsail-network/stellar-contract-bindings
installed: yes

$ stellar plugin update
ℹ️ Updating installed plugins
🔄 Updated "lightsail-network/stellar-contract-bindings"
✅ Done!

$ stellar plugin remove lightsail-network/stellar-contract-bindings
✅ Plugin was uninstalled!
```
